 container: 
  args: 
    - "-text=teste" 
  replicas: 2 
  livenessProbe: 
    enabled: true 
    httpGet: 
      enabled: true 
      path: / 
      port: http 
    initialDelaySeconds: 5 
    periodSeconds: 10 
    failureThreshold: 3 
  readinessProbe: 
    enabled: true 
    httpGet: 
      enabled: true 
      path: /  
      port: http 
    initialDelaySeconds: 5 
    periodSeconds: 10 
    successThreshold: 3 
    failureThreshold: 3 
  ports: 
    - name: http 
      containerPort: 8080
  resources: 
    enabled: true 
    limits:  
      cpu: 250m  
      memory: 32Mi