apiVersion: v1
kind: Service
metadata:
  name: {{ include "webapi.fullname" . }}
  labels:
    {{- include "webapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: 'http'
  selector:
    {{- include "webapi.selectorLabels" . | nindent 4 }}