apiVersion: v1
kind: Service
metadata:
  name: {{ include "webapi.fullname" . }}
  labels:
    {{- include "webapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}  # NodePort ou ClusterIP definido no values.yaml
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}  # Porta do serviço exposta (8080)
      targetPort: {{ .Values.service.port }}  # Porta no container (8080)
      nodePort: {{ .Values.service.nodePort }}  # Porta NodePort (ex: 30000)
      name: 'http'
  selector:
    {{- include "webapi.selectorLabels" . | nindent 4 }}